services:
  app:
    image: shared-ledger:${IMAGE_HASH:-latest}
    build: .
    ports:
      - 8090:8090
    volumes:
      - db_data:/app/pb_data
    deploy:
      update_config:
        order: start-first

volumes:
  db_data:
