name: shared_ledger
description: "Track Shared Expenses with Ease"
publish_to: "none"
version: 1.0.1+18

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.1
  go_router: ^14.6.0
  easy_localization: ^3.0.7
  mocktail: ^1.0.4
  shared_preferences: ^2.3.3
  email_validator: ^3.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  collection: ^1.18.0
  flutter_launcher_icons: ^0.14.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  go_router_builder: any
  build_runner: ^2.4.13
  build_verify: any
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icon.png
